export const MOVIE_LOAD_DATA = 'MOVIE_LOAD_DATA'
export const MOVIE_LOAD_DATA_REQUEST = (id) => `MOVIE_${id}_LOAD_DATA_REQUEST`
export const MOVIE_SET_DATA = 'MOVIE_SET_DATA'
export const MOVIE_DELETE_ALL_DATA = 'MOVIE_DELETE_ALL_DATA'
export const MOVIE_SET_LOADING = 'MOVIE_SET_LOADING'
